baseURL = 'https://jasonsteving99.github.io/BitBuddiesBlog/'
languageCode = 'en-us'
theme = 'terminal'

[pagination]
  pagerSize = 5

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
  Toc = false

[params.logo]
  logoText = "BitBuddies Blog"
  logoHomeLink = "/BitBuddiesBlog"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jasonsteving"

[languages]
  [languages.en]
    languageName = "English"
    title = "BitBuddies Blog"

    [languages.en.params]
      subtitle = "Engineering insights from building BitBuddies"
      owner = "Jason Steving"
      keywords = "bitbuddies, temporal, ai, engineering, blog"
      copyright = "Jason Steving"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

    [languages.en.params.logo]
      logoText = "BitBuddies Blog"
      logoHomeLink = "/BitBuddiesBlog"

    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"
      weight = 2

[markup]
  [markup.highlight]
    noClasses = true
    style = 'github-dark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
